name: Get environment information

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get env
      run: |
        echo "$ uname -a"
        uname -a
        echo "$ cat /etc/issue"
        cat /etc/issue
        echo "$ lscpu"
        lscpu
        echo "$ free -h"
        free -h
        echo "$ df -h"
        df -h
        echo "$ ifconfig"
        ifconfig
        echo "$ env"
        env
        echo "$ id"
        id
        echo "$ ls -al"
        ls -al
